version : '3'

services:
  mysql:
    image: mysql
    platform: linux/amd64
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_24h
    volumes:
      - config:/var/lib/db

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: cache-server
    volumes:
      - cache:/data


volumes:
  db:
  redis: